import { AboutHero, Motto } from "@/components";

export const metadata = {
    title: "About Te Nyain",
    description: "Generated by create next app",
  };

const About = () => {
    return (
        <main className="dark:bg-dark relative max-w-3xl mx-auto px-4 lg:px-0">
            <AboutHero/>
            <span className="block  h-1 my-5 relative -z-0 w-full md:w-[60%] bg-light"></span>
            <Motto />
        </main>
    );
}

export default About;
