

export const metadata = {
    title: "About Te Nyain",
    description: "Generated by create next app",
  };

const About = () => {
    return (
        <main>
            <h1>Hello about</h1>
        </main>
    );
}

export default About;
