import "./globals.css";
import "./style.css";
import { inter } from "./fonts";

import { NavBar } from "@/components";

import Providers from "./providers";

export const metadata = {
  title: "TN Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-dark`}>
        <Providers>
          <NavBar />
          <span className="mt-28 block"></span>
          {children}
        </Providers>
      </body>
    </html>
  );
}

// text-dark dark:bg-dark dark:text-white
